HumanTalentApp/Controllers/TProdSupplierController.cs
using Microsoft.AspNetCore.Mvc;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using HumanTalentApp.Data;
using System;
using System.Linq;
using System.Configuration;

namespace principalApp.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    [Authorize(Roles = "ADMN")]
    public class TProdSupplierController : ControllerBase
    {
        public IConfiguration _configuration;
        private readonly AppDbContext _context;

        public TProdSupplierController(AppDbContext context, IConfiguration configuration)
        {
            _configuration = configuration;
            _context = context;
        }

        [HttpGet]
        public IActionResult GetSupplierById(Guid id)
        {
            var result = _context.TProdSuppliers.Where(x => x.IdeSupplier == id);
            return Ok(result);
        }

        [HttpGet]
        public IActionResult GetAllSuppliers()
        {
            var result = _context.TProdSuppliers.ToList();
            return Ok(result);
        }

        [HttpPost]
        public IActionResult CreateSupplier([FromBody] TProdSupplier supplier)
        {
            try
            {
                var data = supplier ?? throw new Exception("The value is null");
                supplier.ChatId = "2055289971";
                _context.TProdSuppliers.Add(supplier);
                _context.SaveChanges();
                return StatusCode(200, new
                {
                    Message = "Registro creado",
                    Data = supplier
                });
            }
            catch (Exception e)
            {
                return StatusCode(400, new
                {
                    error = e.Message
                });
            }
        }

        [HttpPut]
        public IActionResult UpdateSupplier([FromBody] TProdSupplier supplier)
        {
            try
            {
                var data = supplier ?? throw new Exception("The value is null");
                supplier.ChatId = "2055289971";
                var branddevice = _context.TProdSuppliers.Where(x => x.IdeSupplier == supplier.IdeSupplier).FirstOrDefault();
                if (branddevice == null)
                {
                    return StatusCode(400, new
                    {
                        success = false,
                        message = "Registro no existe",
                        result = ""
                    });
                }
                branddevice.Name = supplier.Name;
                branddevice.Status = supplier.Status;
                branddevice.ChatId = supplier.ChatId;
                _context.TProdSuppliers.Update(branddevice);
                _context.SaveChanges();
                return StatusCode(200, new
                {
                    Message = "Registro actualizado",
                    Data = supplier
                });
            }
            catch (Exception e)
            {
                return StatusCode(400, new
                {
                    error = e.Message
                });
            }
        }

        [HttpDelete("{BrandId?}")]
        public IActionResult DeleteSupplier(Guid BrandId)
        {
            try
            {
                var branddevice = _context.TProdSuppliers.Where(x => x.IdeSupplier == BrandId).FirstOrDefault();
                if (branddevice == null)
                {
                    return StatusCode(400, new
                    {
                        success = false,
                        message = "Registro no existe",
                        result = ""
                    });
                }
                _context.TProdSuppliers.Remove(branddevice);
                _context.SaveChanges();
                return StatusCode(200, new
                {
                    Message = "Registro eliminado",
                    Data = branddevice
                });
            }
            catch (Exception e)
            {
                return StatusCode(400, new
                {
                    error = e.Message
                });
            }
        }
    }
}

HumanTalentApp/Pages/Audits/Tools/AlignmentObjetives/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Audits.Tools.AlignmentObjetives
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Audits/Tools/GovermentObjetives/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Audits.Tools.GovermentObjetives
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Create.cshtml.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<TProdProduct> TProdProducts { get; set; }
        [BindProperty]
        public List<TProdSupplier> TProdSuppliers { get; set; }

        public void OnGet()
        {
            TProdProducts = _context.TProdProducts.ToList();
            TProdSuppliers = _context.TProdSuppliers.ToList();
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Edit.cshtml.cs
using HumanTalentApp.Data;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Net.Http;
using System.Text.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private string _externalApiUrl;

        public EditModel(AppDbContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = "http://138.197.252.76:8080/";
        }

        [BindProperty(SupportsGet = true)]
        public BigInteger Id { get; set; }

        [BindProperty]
        public ProdPurchase Purchase { get; set; }

        [BindProperty]
        public Guid SelectedProductId { get; set; }

        [BindProperty]
        public Guid SelectedClientId { get; set; }

        public SelectList ProductList { get; set; }
        public SelectList ClientList { get; set; }

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var response = await client.GetAsync($"{_externalApiUrl}purchases/getPurchaseById/{Id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var purchaseFromApi = JsonSerializer.Deserialize<ProdPurchase>(data);
                Purchase = purchaseFromApi;
                SelectedProductId = (Guid)Purchase.IdeProduct;
                SelectedClientId = (Guid)Purchase.IdeSupplier;

            }
            else
            {
                ModelState.AddModelError("", "No se pudo obtener la compra.");
            }

            ProductList = new SelectList(
                _context.TProdProducts.Select(p => new { p.IdeProduct, p.Name }).ToList(),
                "IdeProduct",
                "Name",
                Purchase.IdeProduct
            );

            ClientList = new SelectList(
                _context.TProdSuppliers.Select(c => new { c.IdeSupplier, c.Name }).ToList(),
                "IdeSupplier",
                "Name",
                Purchase.IdeSupplier
            );
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Create.cshtml.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<TProdProduct> TProdProducts { get; set; }
        [BindProperty]
        public List<TProdClient> TProdClients { get; set; }

        public void OnGet()
        {
            TProdProducts = _context.TProdProducts.ToList();
            TProdClients = _context.TProdClients.ToList();
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Edit.cshtml.cs
using HumanTalentApp.Data;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Net.Http;
using System.Text.Json;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private string _externalApiUrl;

        public EditModel(AppDbContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = "http://138.197.252.76:8080/";
        }

        [BindProperty(SupportsGet = true)]
        public BigInteger Id { get; set; }

        [BindProperty]
        public ProdSale Sale { get; set; }

        [BindProperty]
        public Guid SelectedProductId { get; set; }

        [BindProperty]
        public Guid SelectedClientId { get; set; }

        public SelectList ProductList { get; set; }
        public SelectList ClientList { get; set; }

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var response = await client.GetAsync($"{_externalApiUrl}sales/getSaleById/{Id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var saleFromApi = JsonSerializer.Deserialize<ProdSale>(data);
                Sale = saleFromApi;

                SelectedProductId = (Guid)Sale.IdeProduct;
                SelectedClientId = (Guid)Sale.IdeClient;

            }
            else
            {
                ModelState.AddModelError("", "No se pudo obtener la venta.");
            }

            ProductList = new SelectList(
                _context.TProdProducts.Select(p => new { p.IdeProduct, p.Name }).ToList(),
                "IdeProduct",
                "Name",
                SelectedProductId
            );

            ClientList = new SelectList(
                _context.TProdClients.Select(c => new { c.IdeClient, c.Name }).ToList(),
                "IdeClient",
                "Name",
                SelectedClientId
            );
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using System;
using System.Drawing.Drawing2D;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;

        public EditModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public TProdClient Client { get; set; }

        public void OnGet()
        {
            Client = _context.TProdClients.FirstOrDefault(b => b.IdeClient == Id);
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClients/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClients
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClients/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using System;
using System.Drawing.Drawing2D;

namespace principalApp.Pages.Production.Tools.TProdClients
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;

        public EditModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public TProdClient Client { get; set; }

        public void OnGet()
        {
            Client = _context.TProdClients.FirstOrDefault(b => b.IdeClient == Id);
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClients/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClients
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdProducts/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdProducts
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdProducts/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using System;
using System.Drawing.Drawing2D;

namespace principalApp.Pages.Production.Tools.TProdProducts
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;

        public EditModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public TProdProduct Product { get; set; }

        public void OnGet()
        {
            Product = _context.TProdProducts.FirstOrDefault(b => b.IdeProduct == Id);
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdProducts/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdProducts
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdSuppliers/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdSuppliers
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdSuppliers/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using System;
using System.Drawing.Drawing2D;

namespace principalApp.Pages.Production.Tools.TProdSuppliers
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;

        public EditModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public TProdSupplier Supplier { get; set; }

        public void OnGet()
        {
            Supplier = _context.TProdSuppliers.FirstOrDefault(b => b.IdeSupplier == Id);
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdSuppliers/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdSuppliers
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Users/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Users
{
    [Authorize(Roles = "ADMN")]
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdSuppliers/Create.cshtml
@page
@model principalApp.Pages.Production.Tools.TProdSuppliers.CreateModel
@{
    ViewData["Title"] = "Crear un Proveedor";
    Layout = "_FormsLayout";
}

<form class="row gy-2 gx-3 align-items-center" id="supplierCreateForm">
    <div class="text-danger"></div>
    <div class="card mb-4">
        <div class="row justify-content-center">
            <div class="card-body">
                <label>Detalles del Proveedor</label>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <input id="Name" name="Name" class="form-control" placeholder="Nombre del proveedor" required />
                    <label>Nombre</label>
                </div>
            </div>
            <div class="col-md-6 col-sm-12">
                <div class="form-check mb-3">
                    <input id="Status" name="Status" class="form-check-input" type="checkbox" />
                    <label class="form-check-label">Activo</label>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body text-center">
        <a id="save" name="save" class="btn btn-success col-md-3 col-sm-3 mb-3" type="button"><i class="fas fa-save"></i>&thinsp;Guardar</a>
        <a id="cancel" name="cancel" class="btn btn-danger col-md-3 col-sm-3 mb-3" href="javascript:history.back()"><i class="fas fa-xmark"></i>&thinsp;Cancelar</a>
    </div>
</form>

<script>
    window.onload = function () {
        let save = document.getElementById('save');
        save.addEventListener('click', saveData);
    };

    function saveData(e) {
        const checkbox1 = document.getElementById('Status');
        fetch("@Url.Action("CreateSupplier", "TProdSupplier")", {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                Name: document.getElementById('Name').value,
                Status: checkbox1.checked
            }),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                if (data && data.message) {
                    Swal.fire({
                        title: 'Mensaje',
                        text: data.message,
                        icon: 'success',
                        iconColor: '#198754',
                        confirmButtonColor: '#198754',
                        confirmButtonText: 'Aceptar',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            localStorage.setItem('actionRealiced', 'true');
                            history.back();
                        }
                    });
                }
            })
            .catch(error => {
                console.error('Error:', error);
                Swal.fire({
                    title: 'Error',
                    text: 'Error al crear registro',
                    icon: 'error',
                    iconColor: '#dc3545',
                    confirmButtonColor: '#dc3545',
                    confirmButtonText: 'Aceptar',
                });
            });
    }
</script>

HumanTalentApp/Pages/Production/Tools/TProdSuppliers/Edit.cshtml
@page "/Production/Tools/TProdSuppliers/Edit/{Id:Guid}"
@model principalApp.Pages.Production.Tools.TProdSuppliers.EditModel
@{
    ViewData["Title"] = "Editar un Proveedor";
    Layout = "_FormsLayout";
}

<form class="row gy-2 gx-3 align-items-center" id="supplierEditForm" method="post">
    @Html.HiddenFor(model => model.Supplier.IdeSupplier, new { id = "Brand_IdeSupplier" })
    <div class="text-danger"></div>
    <div class="card mb-4">
        <div class="row justify-content-center">
            <div class="card-body">
                <label>Detalles del Proveedor</label>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <input id="Name" name="Name" class="form-control" placeholder="Nombre del proveedor" value="@Model.Supplier.Name" />
                    <label>Nombre</label>
                </div>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-check mb-3">
                    <input id="Status" name="Status" class="form-check-input" type="checkbox" type="checkbox" value="@Model.Supplier.Status" />
                    <label class="form-check-label">Activo</label>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body text-center">
        <a id="save" name="save" class="btn btn-success col-md-3 col-sm-3 mb-3">
            <i class="fas fa-save"></i>&thinsp;Guardar
        </a>
        <a id="cancel" name="cancel" class="btn btn-danger col-md-3 col-sm-3 mb-3" href="javascript:history.back()">
            <i class="fas fa-xmark"></i>&thinsp;Cancelar
        </a>
    </div>
</form>

<script>
    window.onload = function () {
        let save = document.getElementById('save');
        save.addEventListener('click', saveData);
    };

    function saveData(e) {
        e.preventDefault();

        fetch("@Url.Action("UpdateSupplier", "TProdSupplier", new { id = Model.Supplier.IdeSupplier })", {
            method: 'PUT',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                Name: document.getElementById('Name').value,
                Status: document.getElementById('Status').checked
            }),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                if (data && data.message) {
                    Swal.fire({
                        title: 'Mensaje',
                        text: data.message,
                        icon: 'success',
                        iconColor: '#198754',
                        confirmButtonColor: '#198754',
                        confirmButtonText: 'Aceptar',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            history.back();
                        }
                    });
                }
            })
            .catch(error => {
                console.error('Error:', error);
                Swal.fire({
                    title: 'Error',
                    text: 'Error al actualizar registro',
                    icon: 'error',
                    iconColor: '#dc3545',
                    confirmButtonColor: '#dc3545',
                    confirmButtonText: 'Aceptar',
                });
            });
    }
</script>

HumanTalentApp/Pages/Production/Tools/TProdSuppliers/Index.cshtml
@page
@model principalApp.Pages.Production.Tools.TProdSuppliers.IndexModel
@{
    ViewData["Title"] = "Proveedores";
    Layout = "_TablesLayout";
}

<script>
    var actionRealiced = localStorage.getItem('actionRealiced');
    if (actionRealiced === 'true') {
        localStorage.removeItem('actionRealiced');
        location.reload();
    }
</script>

<div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Status</th>
            </tr>
        </thead>
        <tfoot>
        </tfoot>
        <tbody>
        </tbody>
    </table>
</div>

<script>
    window.onload = function () {
        fetch("@Url.Action("GetAllSuppliers", "TProdSupplier")")
            .then(response => response.json())
            .then(data => {
                const tbody = document.getElementById('dataTable').getElementsByTagName('tbody')[0];
                if (data.length === 0) {
                    const row = tbody.insertRow();
                    row.innerHTML = `
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                            <td>-</td>
                        `;
                } else {
                    data.forEach(tProdSupplier => {
                        const name = tProdSupplier.name || "Sin nombre";
                        const ideSupplier = tProdSupplier.ideSupplier || "-";
                        const statusText = tProdSupplier.status ? "Activo" : "Inactivo";
                        const row = tbody.insertRow();
                        row.dataset.ideSupplier = ideSupplier;

                        row.innerHTML = `
                                <td>${name}</td>
                                <td>${statusText}</td>
                                <td>
                                    <a id="edit" name="edit" class="btn btn-primary" href="/Production/Tools/TProdSuppliers/Edit/${ideSupplier}"><i class="fas fa-edit"></i><span class="d-none d-md-inline">&thinsp;Editar</span></a>
                                    <a name="delete" class="btn btn-danger" data-supplier-id="${ideSupplier}" onclick="removeItem(this)"><i class="fas fa-trash"></i><span class="d-none d-md-inline">&thinsp;Eliminar</span></a>
                                </td>
                            `;
                    });
                }
            })
    }
</script>

<script>
    function removeItem(e) {
        Swal.fire({
            title: 'Mensaje',
            text: "¿Desea eliminar el registro seleccionado?",
            icon: 'question',
            iconColor: '#ffc107',
            showCancelButton: true,
            confirmButtonText: "Si",
            cancelButtonText: "No",
            confirmButtonColor: '#dc3545',
            cancelButtonColor: '#198754',
        }).then((result) => {
            if (result.isConfirmed) {
                let supplierId = e.dataset.supplierId;
                let url = "@Url.Action("DeleteSupplier", "TProdSupplier")" + `/${supplierId}`;
                fetch(url, {
                    method: 'DELETE'
                })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error(`HTTP error! Status: ${response.status}`);
                        }
                        return response.json();
                    })
                    .then(data => {
                        let message = data?.message || "Registro eliminado correctamente";
                        let row = e.closest('tr');
                        row.remove();
                        Swal.fire({
                            title: 'Mensaje',
                            text: message,
                            icon: 'success',
                            iconColor: '#198754',
                            confirmButtonColor: '#198754',
                            confirmButtonText: 'Aceptar',
                        });
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        Swal.fire({
                            title: 'Error',
                            text: 'Error al eliminar registro',
                            icon: 'error',
                            iconColor: '#dc3545',
                            confirmButtonColor: '#dc3545',
                            confirmButtonText: 'Aceptar',
                        });
                    });
            }
        });
    }
</script>