HumanTalentApp/Controllers/ProdSalesController.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using HumanTalentApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;

namespace principalApp.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    [Authorize(Roles = "ADMN,PROD")]
    public class ProdSalesController : ControllerBase
    {
        public IConfiguration _configuration;
        private readonly AppDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private static string _externalApiUrl;
        private static string _producerApiUrl;

        public ProdSalesController(AppDbContext context, IConfiguration configuration, IHttpClientFactory httpClientFactory)
        {
            _configuration = configuration;
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = _configuration.GetValue<string>("AppSettings:managementApi");
            _producerApiUrl = _configuration.GetValue<string>("AppSettings:producerApi");
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetSaleById(long id)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.GetAsync($"{_externalApiUrl}sales/getSaleById/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetAllSales()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.GetAsync($"{_externalApiUrl}sales/getSales");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        public async Task<IActionResult> GetAllSalesWithNames()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.GetAsync($"{_externalApiUrl}sales/getSales");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var sales = JsonSerializer.Deserialize<List<ProdSale>>(data);

                    var productIds = sales.Select(s => s.IdeProduct).Distinct().ToList();
                    var products = await _context.TProdProducts
                        .Where(p => productIds.Contains(p.IdeProduct))
                        .ToListAsync();

                    var clientIds = sales.Select(s => s.IdeClient).Distinct().ToList();
                    var clients = await _context.TProdClients
                        .Where(c => clientIds.Contains(c.IdeClient))
                        .ToListAsync();

                    var result = sales.Select(s => new
                    {
                        s.IdeSale,
                        ProductName = products.FirstOrDefault(prod => prod.IdeProduct == s.IdeProduct)?.Name ?? "Desconocido",
                        ClientName = clients.FirstOrDefault(c => c.IdeClient == s.IdeClient)?.Name ?? "Desconocido",
                        s.Quantity,
                        IsPrincipal = s.Quantity > 0
                    }).ToList();

                    return Ok(result);
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddSale([FromBody] ProdSale sale)
        {
            try
            {
                if (sale == null || sale.IdeClient == null || sale.IdeProduct == null || sale.Quantity <= 0)
                {
                    return BadRequest("El modelo enviado tiene valores inválidos.");
                }
                var client = _httpClientFactory.CreateClient();
                sale.IdeSale = null;
                var response = await client.PostAsJsonAsync($"{_externalApiUrl}sales/addSale", sale);

                if (response.IsSuccessStatusCode)
                {   
                    TProdClient findClient =  _context.TProdClients.Where(x => x.IdeClient == sale.IdeClient).FirstOrDefault();

                    TProdProduct findProduct = _context.TProdProducts.Where(x => x.IdeProduct == sale.IdeProduct).FirstOrDefault();

                    MessageModel newMessage = new MessageModel() {
                        IdClient= findClient.ChatId,
                        Name = findClient.Name,
                        ProductName = findProduct.Name,
                        ProductQuantity= sale.Quantity,
                        Description= "Agregado"
                    };
                    var message = await client.PostAsJsonAsync($"{_producerApiUrl}message/sendTopicSale", newMessage);
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpPut]
        public async Task<IActionResult> UpdateSale([FromBody] ProdSale sale)
        {
            try
            {
                if (sale == null || sale.IdeClient == null || sale.IdeProduct == null || sale.Quantity <= 0)
                {
                    return BadRequest("El modelo enviado tiene valores inválidos.");
                }

                var client = _httpClientFactory.CreateClient();
                var response = await client.PutAsJsonAsync($"{_externalApiUrl}sales/editSale", sale);

                if (response.IsSuccessStatusCode)
                {
                    TProdClient findClient = _context.TProdClients.Where(x => x.IdeClient == sale.IdeClient).FirstOrDefault();

                    TProdProduct findProduct = _context.TProdProducts.Where(x => x.IdeProduct == sale.IdeProduct).FirstOrDefault();

                    MessageModel newMessage = new MessageModel()
                    {
                        IdClient = findClient.ChatId,
                        Name = findClient.Name,
                        ProductName = findProduct.Name,
                        ProductQuantity = sale.Quantity,
                        Description = "Actualizado"
                    };
                    var message = await client.PostAsJsonAsync($"{_producerApiUrl}message/sendTopicSale", newMessage);
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteSale(long id)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.DeleteAsync($"{_externalApiUrl}sales/deleteSale/{id}");

                if (response.IsSuccessStatusCode)
                {
                    return Ok(new { message = "Eliminado Exitosamente" });
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Create.cshtml.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<TProdProduct> TProdProducts { get; set; }
        [BindProperty]
        public List<TProdSupplier> TProdSuppliers { get; set; }

        public void OnGet()
        {
            TProdProducts = _context.TProdProducts.ToList();
            TProdSuppliers = _context.TProdSuppliers.ToList();
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Edit.cshtml.cs
using HumanTalentApp.Data;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Net.Http;
using System.Text.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private string _externalApiUrl;

        public EditModel(AppDbContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = "http://138.197.252.76:8080/";
        }

        [BindProperty(SupportsGet = true)]
        public BigInteger Id { get; set; }

        [BindProperty]
        public ProdPurchase Purchase { get; set; }

        [BindProperty]
        public Guid SelectedProductId { get; set; }

        [BindProperty]
        public Guid SelectedClientId { get; set; }

        public SelectList ProductList { get; set; }
        public SelectList ClientList { get; set; }

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var response = await client.GetAsync($"{_externalApiUrl}purchases/getPurchaseById/{Id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var purchaseFromApi = JsonSerializer.Deserialize<ProdPurchase>(data);
                Purchase = purchaseFromApi;
                SelectedProductId = (Guid)Purchase.IdeProduct;
                SelectedClientId = (Guid)Purchase.IdeSupplier;

            }
            else
            {
                ModelState.AddModelError("", "No se pudo obtener la compra.");
            }

            ProductList = new SelectList(
                _context.TProdProducts.Select(p => new { p.IdeProduct, p.Name }).ToList(),
                "IdeProduct",
                "Name",
                Purchase.IdeProduct
            );

            ClientList = new SelectList(
                _context.TProdSuppliers.Select(c => new { c.IdeSupplier, c.Name }).ToList(),
                "IdeSupplier",
                "Name",
                Purchase.IdeSupplier
            );
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Create.cshtml.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<TProdProduct> TProdProducts { get; set; }
        [BindProperty]
        public List<TProdClient> TProdClients { get; set; }

        public void OnGet()
        {
            TProdProducts = _context.TProdProducts.ToList();
            TProdClients = _context.TProdClients.ToList();
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Edit.cshtml.cs
using HumanTalentApp.Data;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Net.Http;
using System.Text.Json;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private string _externalApiUrl;

        public EditModel(AppDbContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = "http://138.197.252.76:8080/";
        }

        [BindProperty(SupportsGet = true)]
        public BigInteger Id { get; set; }

        [BindProperty]
        public ProdSale Sale { get; set; }

        [BindProperty]
        public Guid SelectedProductId { get; set; }

        [BindProperty]
        public Guid SelectedClientId { get; set; }

        public SelectList ProductList { get; set; }
        public SelectList ClientList { get; set; }

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var response = await client.GetAsync($"{_externalApiUrl}sales/getSaleById/{Id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var saleFromApi = JsonSerializer.Deserialize<ProdSale>(data);
                Sale = saleFromApi;

                SelectedProductId = (Guid)Sale.IdeProduct;
                SelectedClientId = (Guid)Sale.IdeClient;

            }
            else
            {
                ModelState.AddModelError("", "No se pudo obtener la venta.");
            }

            ProductList = new SelectList(
                _context.TProdProducts.Select(p => new { p.IdeProduct, p.Name }).ToList(),
                "IdeProduct",
                "Name",
                SelectedProductId
            );

            ClientList = new SelectList(
                _context.TProdClients.Select(c => new { c.IdeClient, c.Name }).ToList(),
                "IdeClient",
                "Name",
                SelectedClientId
            );
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using System;
using System.Drawing.Drawing2D;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;

        public EditModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public TProdClient Client { get; set; }

        public void OnGet()
        {
            Client = _context.TProdClients.FirstOrDefault(b => b.IdeClient == Id);
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Create.cshtml
@page
@model HumanTalentApp.Pages.Production.Sales.CreateModel
@{
    ViewData["Title"] = "Crear Venta";
    Layout = "_FormsLayout";
}

<form class="row gy-2 gx-3 align-items-center" id="purchaseCreateForm">
    <div class="text-danger"></div>
    <div class="card mb-4">
        <div class="row justify-content-center">
            <div class="card-body">
                <label>Detalles de la Compra</label>
            </div>

            <!-- Selector de Producto -->
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="ProductSelect" name="ProductSelect" class="form-control" required>
                        <option value="">Seleccione un Producto</option>
                        @foreach (var product in Model.TProdProducts)
                        {
                            <option value="@product.IdeProduct">@product.Name</option>
                        }
                    </select>
                    <label for="ProductSelect">Producto</label>
                </div>
            </div>

            <!-- Selector de Proveedor -->
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="SupplierSelect" name="SupplierSelect" class="form-control" required>
                        <option value="">Seleccione un Cliente</option>
                        @foreach (var client in Model.TProdClients)
                        {
                            <option value="@client.IdeClient">@client.Name</option>
                        }
                    </select>
                    <label for="SupplierSelect">Cliente</label>
                </div>
            </div>

            <!-- Cantidad -->
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <input id="Quantity" name="Quantity" class="form-control" type="number" placeholder="Cantidad" required />
                    <label for="Quantity">Cantidad</label>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body text-center">
        <a id="save" name="save" class="btn btn-success col-md-3 col-sm-3 mb-3"><i class="fas fa-save"></i>&thinsp;Guardar</a>
        <a id="cancel" name="cancel" class="btn btn-danger col-md-3 col-sm-3 mb-3" href="javascript:history.back()"><i class="fas fa-xmark"></i>&thinsp;Cancelar</a>
    </div>
</form>

<script>
    window.onload = function () {
        let save = document.getElementById('save');
        save.addEventListener('click', saveData);
    };

    function saveData(e) {
        const productSelect = document.getElementById('ProductSelect');
        const supplierSelect = document.getElementById('SupplierSelect');
        const quantity = document.getElementById('Quantity').value;

        fetch("@Url.Action("AddSale", "ProdSales")", {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                IdeProduct: productSelect.value,
                IdeClient: supplierSelect.value,
                Quantity: quantity
            }),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                if (data) {
                    Swal.fire({
                        title: 'Mensaje',
                        text: "Registro Exitoso",
                        icon: 'success',
                        iconColor: '#198754',
                        confirmButtonColor: '#198754',
                        confirmButtonText: 'Aceptar',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            localStorage.setItem('actionRealiced', 'true');
                            history.back();
                        }
                    });
                }
            })
            .catch(error => {
                console.error('Error:', error);
                Swal.fire({
                    title: 'Error',
                    text: 'Error al crear la compra',
                    icon: 'error',
                    iconColor: '#dc3545',
                    confirmButtonColor: '#dc3545',
                    confirmButtonText: 'Aceptar',
                });
            });
    }
</script>

HumanTalentApp/Pages/Production/Sales/Edit.cshtml
@page "/Production/Sales/Edit/{Id:long}"
@model HumanTalentApp.Pages.Production.Sales.EditModel
@{
    ViewData["Title"] = "Editar Venta";
    Layout = "_FormsLayout";
}

<form class="row gy-2 gx-3 align-items-center" id="orderRepair" method="post">
    @Html.HiddenFor(model => model.Sale.IdeSale)
    <div class="text-danger"></div>
    <div class="card mb-4">
        <div class="row justify-content-center">
            <div class="card-body">
                <label>Detalles</label>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <input id="Quantity" name="Quantity" class="form-control" placeholder="Quantity" value="@Model.Sale.Quantity" />
                    <label>Quantity</label>
                </div>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="SelectedProductId" name="SelectedProductId" class="form-select" aria-label="Select Product">
                        <option value="">Seleccione un Producto</option>
                        @foreach (var product in Model.ProductList)
                        {
                            <option value="@product.Value" selected="@(product.Value == Model.Sale.IdeProduct.ToString() ? "selected" : "")">
                                @product.Text
                            </option>
                        }
                    </select>
                    <label>Producto</label>
                </div>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="SelectedClientId" name="SelectedClientId" class="form-select" aria-label="Select Supplier">
                        <option value="">Seleccione un Proveedor</option>
                        @foreach (var client in Model.ClientList)
                        {
                            <option value="@client.Value" selected="@(client.Value == Model.Sale.IdeSale.ToString() ? "selected" : "")">
                                @client.Text
                            </option>
                        }
                    </select>
                    <label>Proveedor</label>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body text-center">
        <a id="save" name="save" class="btn btn-success col-md-3 col-sm-3 mb-3"><i class="fas fa-save"></i>&thinsp;Guardar</a>
        <a id="cancel" name="cancel" class="btn btn-danger col-md-3 col-sm-3 mb-3" href="javascript:history.back()"><i class="fas fa-xmark"></i>&thinsp;Cancelar</a>
    </div>
</form>

<script>
    window.onload=function () {
        let save = document.getElementById('save');
        save.addEventListener('click', saveData);
    };

    function saveData(e) {
        const productId = document.getElementById('SelectedProductId').value;
        const clientId = document.getElementById('SelectedClientId').value;
        const quantity = document.getElementById('Quantity').value;

        fetch("@Url.Action("UpdateSale", "ProdSales")", {
            method: 'PUT',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                IdeSale: document.getElementById('Sale_IdeSale').value,
                IdeProduct: productId,
                IdeClient: clientId,
                Quantity: quantity
            }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error(`HTTP error! Status: ${response.status}`);
            }
            return response.json();
        })
        .then(data => {
            if (data) {
                Swal.fire({
                    title: 'Mensaje',
                    text: "Actualizado con Éxito",
                    icon: 'success',
                    iconColor: '#198754',
                    confirmButtonColor: '#198754',
                    confirmButtonText: 'Aceptar',
                }).then((result) => {
                    if (result.isConfirmed) {
                        history.back();
                    }
                });
            }
        })
        .catch(error => {
            console.error('Error:', error);
            Swal.fire({
                title: 'Error',
                text: 'Error al actualizar registro',
                icon: 'error',
                iconColor: '#dc3545',
                confirmButtonColor: '#dc3545',
                confirmButtonText: 'Aceptar',
            });
        });
    }
</script>

HumanTalentApp/Pages/Production/Sales/Index.cshtml
@page
@model HumanTalentApp.Pages.Production.Sales.IndexModel
@{
    ViewData["Title"] = "Ventas";
    Layout = "_TablesLayout";
}
<script>
    var actionRealiced = localStorage.getItem('actionRealiced');

    if (actionRealiced === 'true') {
        localStorage.removeItem('actionRealiced');
        location.reload();
    }
</script>
<div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cliente</th>
                <th>Cantidad</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tfoot>
        </tfoot>
        <tbody>
        </tbody>
    </table>
</div>

<script>
    window.onload = function () {
        fetch("@Url.Action("GetAllSalesWithNames", "ProdSales")")
            .then(response => response.json())
            .then(data => {
                const tbody = document.getElementById('dataTable').getElementsByTagName('tbody')[0];
                if (data.length === 0) {
                    const row = tbody.insertRow();
                    row.innerHTML = `
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                        <td>-</td>
                    `;
                } else {
                    data.forEach(sale => {
                        const row = tbody.insertRow();
                        row.dataset.IdeSale = sale.ideSale;
                        row.innerHTML = `
                            <td>${sale.productName}</td>
                            <td>${sale.clientName}</td>
                            <td>${sale.quantity}</td>
                            <td>
                                <a id="edit" name="edit" class="btn btn-primary" href="/Production/Sales/Edit/${sale.ideSale}"><i class="fas fa-edit"></i><span class="d-none d-md-inline">&thinsp;Editar</span></a>
                                <a name="delete" class="btn btn-danger" data-brand-Id="${sale.ideSale}" onclick="removeItem(this)"><i class="fas fa-trash"></i><span class="d-none d-md-inline">&thinsp;Eliminar</span></a>
                            </td>
                        `;
                    });
                }
            });
    }
</script>

<script>
    function removeItem(e) {
        Swal.fire({
            title: 'Mensaje',
            text: "¿Desea eliminar el registro seleccionado?",
            icon: 'question',
            iconColor: '#ffc107',
            showCancelButton: true,
            confirmButtonText: "Si",
            cancelButtonText: "No",
            confirmButtonColor: '#dc3545',
            cancelButtonColor: '#198754',
        }).then((result) => {
            if (result.isConfirmed) {
                let saleId = e.dataset.brandId;
                let url = '/api' + "@Url.Action("DeleteSale", "ProdSales")" + `/${saleId}`;
                fetch(url, {
                    method: 'DELETE',
                    headers: {
                        "Content-Type": "application/json"
                    }
                })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error(`HTTP error! Status: ${response.status}`);
                        }
                        return response.json();
                    })
                    .then(data => {
                        if (data) {
                            let row = e.closest('tr');
                            row.remove();
                            Swal.fire({
                                title: 'Mensaje',
                                text: "Registro eliminado con éxito",
                                icon: 'success',
                                iconColor: '#198754',
                                confirmButtonColor: '#198754',
                                confirmButtonText: 'Aceptar',
                            })
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        Swal.fire({
                            title: 'Error',
                            text: 'Error al eliminar el registro',
                            icon: 'error',
                            iconColor: '#dc3545',
                            confirmButtonColor: '#dc3545',
                            confirmButtonText: 'Aceptar',
                        });
                    });
            }
        });
    }
</script>