HumanTalentApp/Controllers/ProdPurchasesController.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using HumanTalentApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace principalApp.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    [Authorize(Roles = "ADMN,PROD")]
    public class ProdPurchasesController : ControllerBase
    {
        public IConfiguration _configuration;
        private readonly AppDbContext _context;
        private readonly IHttpClientFactory _httpClientFactory;
        private static string _externalApiUrl;
        private static string _producerApiUrl;

        public ProdPurchasesController(AppDbContext context, IConfiguration configuration, IHttpClientFactory httpClientFactory)
        {
            _configuration = configuration;
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = _configuration.GetValue<string>("AppSettings:managementApi");
            _producerApiUrl = _configuration.GetValue<string>("AppSettings:producerApi");
        }

        [HttpGet("{id}")]
        public async Task<IActionResult> GetPurchaseById(long id)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.GetAsync($"{_externalApiUrl}purchases/getPurchaseById/{id}");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetAllPurchases()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.GetAsync($"{_externalApiUrl}purchases/getPurchases");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        public async Task<IActionResult> GetAllPurchasesWithName()
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.GetAsync($"{_externalApiUrl}purchases/getPurchases");

                if (response.IsSuccessStatusCode)
                {
                    var data = await response.Content.ReadAsStringAsync();
                    var purchases = JsonSerializer.Deserialize<List<ProdPurchase>>(data);

                    // Obtener los productos y proveedores desde la base de datos
                    var productIds = purchases.Select(p => p.IdeProduct).Distinct().ToList();
                    var supplierIds = purchases.Select(p => p.IdeSupplier).Distinct().ToList();

                    var products = await _context.TProdProducts
                        .Where(p => productIds.Contains(p.IdeProduct))
                        .ToListAsync();

                    var suppliers = await _context.TProdSuppliers
                        .Where(s => supplierIds.Contains(s.IdeSupplier))
                        .ToListAsync();

                    var result = purchases.Select(p => new
                    {
                        p.IdePurchase,
                        ProductName = products.FirstOrDefault(prod => prod.IdeProduct == p.IdeProduct)?.Name ?? "Desconocido",
                        SupplierName = suppliers.FirstOrDefault(sup => sup.IdeSupplier == p.IdeSupplier)?.Name ?? "Desconocido",
                        p.Quantity,
                        isPrincipal = p.Quantity > 0
                    }).ToList();

                    return Ok(result);
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddPurchase([FromBody] ProdPurchase purchase)
        {
            try
            {
                if (purchase == null || purchase.IdeSupplier == null || purchase.IdeProduct == null || purchase.Quantity <= 0)
                {
                    return BadRequest("El modelo enviado tiene valores inválidos.");
                }

                var client = _httpClientFactory.CreateClient();
                var response = await client.PostAsJsonAsync($"{_externalApiUrl}purchases/addPurchase", purchase);

                if (response.IsSuccessStatusCode)
                {
                    TProdSupplier findSupplier = _context.TProdSuppliers.Where(x => x.IdeSupplier == purchase.IdeSupplier).FirstOrDefault();

                    TProdProduct findProduct = _context.TProdProducts.Where(x => x.IdeProduct == purchase.IdeProduct).FirstOrDefault();

                    MessageModel newMessage = new MessageModel()
                    {
                        IdClient = findSupplier.ChatId,
                        Name = findSupplier.Name,
                        ProductName = findProduct.Name,
                        ProductQuantity = purchase.Quantity,
                        Description = "agregado"
                    };
                    var message = await client.PostAsJsonAsync($"{_producerApiUrl}message/sendTopicPurchase", newMessage);
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpPut]
        public async Task<IActionResult> UpdatePurchase([FromBody] ProdPurchase purchase)
        {
            try
            {
                if (purchase == null || purchase.IdeSupplier == null || purchase.IdeProduct == null || purchase.Quantity <= 0)
                {
                    return BadRequest("El modelo enviado tiene valores inválidos.");
                }

                var client = _httpClientFactory.CreateClient();
                var response = await client.PutAsJsonAsync($"{_externalApiUrl}purchases/editPurchase", purchase);

                if (response.IsSuccessStatusCode)
                {
                    TProdSupplier findSupplier = _context.TProdSuppliers.Where(x => x.IdeSupplier == purchase.IdeSupplier).FirstOrDefault();

                    TProdProduct findProduct = _context.TProdProducts.Where(x => x.IdeProduct == purchase.IdeProduct).FirstOrDefault();

                    MessageModel newMessage = new MessageModel()
                    {
                        IdClient = findSupplier.ChatId,
                        Name = findSupplier.Name,
                        ProductName = findProduct.Name,
                        ProductQuantity = purchase.Quantity,
                        Description = "actualizado"
                    };
                    var message = await client.PostAsJsonAsync($"{_producerApiUrl}message/sendTopicPurchase", newMessage);
                    var data = await response.Content.ReadAsStringAsync();
                    return Ok(JsonSerializer.Deserialize<object>(data));
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeletePurchase(long id)
        {
            try
            {
                var client = _httpClientFactory.CreateClient();
                var response = await client.DeleteAsync($"{_externalApiUrl}purchases/deletePurchase/{id}");

                if (response.IsSuccessStatusCode)
                {
                    return Ok(new { message = "Eliminado Exitosamente" });
                }
                else
                {
                    return StatusCode((int)response.StatusCode, response.ReasonPhrase);
                }
            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status500InternalServerError, $"Error interno: {ex.Message}");
            }
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Create.cshtml.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<TProdProduct> TProdProducts { get; set; }
        [BindProperty]
        public List<TProdSupplier> TProdSuppliers { get; set; }

        public void OnGet()
        {
            TProdProducts = _context.TProdProducts.ToList();
            TProdSuppliers = _context.TProdSuppliers.ToList();
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Edit.cshtml.cs
using HumanTalentApp.Data;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Net.Http;
using System.Text.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private string _externalApiUrl;

        public EditModel(AppDbContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = "http://138.197.252.76:8080/";
        }

        [BindProperty(SupportsGet = true)]
        public BigInteger Id { get; set; }

        [BindProperty]
        public ProdPurchase Purchase { get; set; }

        [BindProperty]
        public Guid SelectedProductId { get; set; }

        [BindProperty]
        public Guid SelectedClientId { get; set; }

        public SelectList ProductList { get; set; }
        public SelectList ClientList { get; set; }

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var response = await client.GetAsync($"{_externalApiUrl}purchases/getPurchaseById/{Id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var purchaseFromApi = JsonSerializer.Deserialize<ProdPurchase>(data);
                Purchase = purchaseFromApi;
                SelectedProductId = (Guid)Purchase.IdeProduct;
                SelectedClientId = (Guid)Purchase.IdeSupplier;

            }
            else
            {
                ModelState.AddModelError("", "No se pudo obtener la compra.");
            }

            ProductList = new SelectList(
                _context.TProdProducts.Select(p => new { p.IdeProduct, p.Name }).ToList(),
                "IdeProduct",
                "Name",
                Purchase.IdeProduct
            );

            ClientList = new SelectList(
                _context.TProdSuppliers.Select(c => new { c.IdeSupplier, c.Name }).ToList(),
                "IdeSupplier",
                "Name",
                Purchase.IdeSupplier
            );
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Purchases
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Create.cshtml.cs
using EntityModelsPrincipalApp.Models.App;
using HumanTalentApp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public List<TProdProduct> TProdProducts { get; set; }
        [BindProperty]
        public List<TProdClient> TProdClients { get; set; }

        public void OnGet()
        {
            TProdProducts = _context.TProdProducts.ToList();
            TProdClients = _context.TProdClients.ToList();
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Edit.cshtml.cs
using HumanTalentApp.Data;
using EntityModelsPrincipalApp.Models.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Numerics;
using System.Net.Http;
using System.Text.Json;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class EditModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private string _externalApiUrl;

        public EditModel(AppDbContext context, IHttpClientFactory httpClientFactory)
        {
            _context = context;
            _httpClientFactory = httpClientFactory;
            _externalApiUrl = "http://138.197.252.76:8080/";
        }

        [BindProperty(SupportsGet = true)]
        public BigInteger Id { get; set; }

        [BindProperty]
        public ProdSale Sale { get; set; }

        [BindProperty]
        public Guid SelectedProductId { get; set; }

        [BindProperty]
        public Guid SelectedClientId { get; set; }

        public SelectList ProductList { get; set; }
        public SelectList ClientList { get; set; }

        public async Task OnGetAsync()
        {
            var client = _httpClientFactory.CreateClient();
            var response = await client.GetAsync($"{_externalApiUrl}sales/getSaleById/{Id}");

            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                var saleFromApi = JsonSerializer.Deserialize<ProdSale>(data);
                Sale = saleFromApi;

                SelectedProductId = (Guid)Sale.IdeProduct;
                SelectedClientId = (Guid)Sale.IdeClient;

            }
            else
            {
                ModelState.AddModelError("", "No se pudo obtener la venta.");
            }

            ProductList = new SelectList(
                _context.TProdProducts.Select(p => new { p.IdeProduct, p.Name }).ToList(),
                "IdeProduct",
                "Name",
                SelectedProductId
            );

            ClientList = new SelectList(
                _context.TProdClients.Select(c => new { c.IdeClient, c.Name }).ToList(),
                "IdeClient",
                "Name",
                SelectedClientId
            );
        }
    }
}

HumanTalentApp/Pages/Production/Sales/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HumanTalentApp.Pages.Production.Sales
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClient/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClient
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Tools/TProdClients/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace principalApp.Pages.Production.Tools.TProdClients
{
    public class CreateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

HumanTalentApp/Pages/Production/Purchases/Create.cshtml
@page
@model HumanTalentApp.Pages.Production.Purchases.CreateModel
@{
    ViewData["Title"] = "Crear Venta";
    Layout = "_FormsLayout";
}

<form class="row gy-2 gx-3 align-items-center" id="purchaseCreateForm">
    <div class="text-danger"></div>
    <div class="card mb-4">
        <div class="row justify-content-center">
            <div class="card-body">
                <label>Detalles de la Venta</label>
            </div>

            <!-- Selector de Producto -->
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="ProductSelect" name="ProductSelect" class="form-control" required>
                        <option value="">Seleccione un Producto</option>
                        @foreach (var product in Model.TProdProducts)
                        {
                            <option value="@product.IdeProduct">@product.Name</option>
                        }
                    </select>
                    <label for="ProductSelect">Producto</label>
                </div>
            </div>

            <!-- Selector de Proveedor -->
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="SupplierSelect" name="SupplierSelect" class="form-control" required>
                        <option value="">Seleccione un Proveedor</option>
                        @foreach (var supplier in Model.TProdSuppliers)
                        {
                            <option value="@supplier.IdeSupplier">@supplier.Name</option>
                        }
                    </select>
                    <label for="SupplierSelect">Proveedor</label>
                </div>
            </div>

            <!-- Cantidad -->
            <div class="col-md-6 col-sm-12">
                <div class="form-floating mb-3">
                    <input id="Quantity" name="Quantity" class="form-control" type="number" placeholder="Cantidad" required />
                    <label for="Quantity">Cantidad</label>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body text-center">
        <a id="save" name="save" class="btn btn-success col-md-3 col-sm-3 mb-3"><i class="fas fa-save"></i>&thinsp;Guardar</a>
        <a id="cancel" name="cancel" class="btn btn-danger col-md-3 col-sm-3 mb-3" href="javascript:history.back()"><i class="fas fa-xmark"></i>&thinsp;Cancelar</a>
    </div>
</form>

<script>
    window.onload = function () {
        let save = document.getElementById('save');
        save.addEventListener('click', saveData);
    };

    function saveData(e) {
        const productSelect = document.getElementById('ProductSelect');
        const supplierSelect = document.getElementById('SupplierSelect');
        const quantity = document.getElementById('Quantity').value;

        fetch("@Url.Action("AddPurchase", "ProdPurchases")", {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                IdeProduct: productSelect.value,
                IdeSupplier: supplierSelect.value,
                Quantity: quantity
            }),
        })
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                }
                return response.json();
            })
            .then(data => {
                if (data) {
                    Swal.fire({
                        title: 'Mensaje',
                        text: "Registro Exitoso",
                        icon: 'success',
                        iconColor: '#198754',
                        confirmButtonColor: '#198754',
                        confirmButtonText: 'Aceptar',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            localStorage.setItem('actionRealiced', 'true');
                            history.back();
                        }
                    });
                }
            })
            .catch(error => {
                console.error('Error:', error);
                Swal.fire({
                    title: 'Error',
                    text: 'Error al crear la compra',
                    icon: 'error',
                    iconColor: '#dc3545',
                    confirmButtonColor: '#dc3545',
                    confirmButtonText: 'Aceptar',
                });
            });
    }
</script>

HumanTalentApp/Pages/Production/Purchases/Edit.cshtml
@page "/Production/Purchases/Edit/{Id:long}"
@model HumanTalentApp.Pages.Production.Purchases.EditModel
@{
    ViewData["Title"] = "Editar Compras";
    Layout = "_FormsLayout";
}

<form class="row gy-2 gx-3 align-items-center" id="orderRepair" method="post">
    @Html.HiddenFor(model => model.Purchase.IdePurchase)
    <div class="text-danger"></div>
    <div class="card mb-4">
        <div class="row justify-content-center">
            <div class="card-body">
                <label>Detalles</label>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <input id="Quantity" name="Quantity" class="form-control" placeholder="quantity" value="@Model.Purchase.Quantity" />
                    <label>Quantity</label>
                </div>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="SelectedProductId" name="SelectedProductId" class="form-select" aria-label="Select Product">
                        <option value="">Seleccione un Producto</option>
                        @foreach (var product in Model.ProductList)
                        {
                            <option value="@product.Value" selected="@(product.Value == Model.Purchase.IdeProduct.ToString() ? "selected" : "")">
                                @product.Text
                            </option>
                        }
                    </select>
                    <label>Producto</label>
                </div>
            </div>
            <div class="col-md-8 col-sm-12">
                <div class="form-floating mb-3">
                    <select id="SelectedClientId" name="SelectedClientId" class="form-select" aria-label="Select Supplier">
                        <option value="">Seleccione un Proveedor</option>
                        @foreach (var client in Model.ClientList)
                        {
                            <option value="@client.Value" selected="@(client.Value == Model.Purchase.IdeSupplier.ToString() ? "selected" : "")">
                                @client.Text
                            </option>
                        }
                    </select>
                    <label>Proveedor</label>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body text-center">
        <a id="save" name="save" class="btn btn-success col-md-3 col-sm-3 mb-3"><i class="fas fa-save"></i>&thinsp;Guardar</a>
        <a id="cancel" name="cancel" class="btn btn-danger col-md-3 col-sm-3 mb-3" href="javascript:history.back()"><i class="fas fa-xmark"></i>&thinsp;Cancelar</a>
    </div>
</form>

<script>
    window.onload=function () {
        let save = document.getElementById('save');
        save.addEventListener('click', saveData);
    };
    function saveData(e) {
        const productId = document.getElementById('SelectedProductId').value;
        const supplierId = document.getElementById('SelectedClientId').value;
        const quantity = document.getElementById('Quantity').value;

        fetch("@Url.Action("UpdatePurchase", "ProdPurchases")", {
            method: 'PUT',
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                IdePurchase: document.getElementById('Purchase_IdePurchase').value,
                IdeProduct: productId,
                IdeSupplier: supplierId,
                Quantity: quantity
            }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error(`HTTP error! Status: ${response.status}`);
            }
            return response.json();
        })
        .then(data => {
            if (data) {
                Swal.fire({
                    title: 'Mensaje',
                    text: "Actualizado con Éxito",
                    icon: 'success',
                    iconColor: '#198754',
                    confirmButtonColor: '#198754',
                    confirmButtonText: 'Aceptar',
                }).then((result) => {
                    if (result.isConfirmed) {
                        history.back();
                    }
                });
            }
        })
        .catch(error => {
            console.error('Error:', error);
            Swal.fire({
                title: 'Error',
                text: 'Error al actualizar registro',
                icon: 'error',
                iconColor: '#dc3545',
                confirmButtonColor: '#dc3545',
                confirmButtonText: 'Aceptar',
            });
        });
    }
</script>